import { Address } from "../address/Address";
import { AppUser } from "../appUser/AppUser";
import { Coupon } from "../coupon/Coupon";
import { Decimal } from "decimal.js";
import { FulfillmentBook } from "../fulfillmentBook/FulfillmentBook";
import { OrderItem } from "../orderItem/OrderItem";
import { OrdersHashtagsMap } from "../ordersHashtagsMap/OrdersHashtagsMap";
import { PaymentMethod } from "../paymentMethod/PaymentMethod";
import { PaymentsBook } from "../paymentsBook/PaymentsBook";
import { Rating } from "../rating/Rating";
import { Restaurant } from "../restaurant/Restaurant";
import { Review } from "../review/Review";
import { SettlementsBreakup } from "../settlementsBreakup/SettlementsBreakup";

export type OrderHistory = {
  addresses?: Address;
  appUsers?: AppUser;
  coupons?: Coupon;
  createdAt: Date | null;
  deliveryTipsAmount: Decimal | null;
  discountAmount: Decimal | null;
  estimatedDeliveryTime: Date | null;
  finalAmount: Decimal | null;
  fulfillmentBook?: Array<FulfillmentBook>;
  id: string;
  isCancelled: boolean | null;
  isFulfilled: boolean | null;
  isPaid: boolean | null;
  isRejected: boolean | null;
  orderDateTime: Date | null;
  orderIdRef: number;
  orderItems?: Array<OrderItem>;
  ordersHashtagsMap?: Array<OrdersHashtagsMap>;
  order_type?: "Delivery" | "TakeAway" | "DineIn" | null;
  packagingAmount: Decimal | null;
  paymentMethods?: PaymentMethod;
  paymentsBook?: Array<PaymentsBook>;
  preparationInstruction: string | null;
  preparationTime: number | null;
  ratings?: Array<Rating>;
  rejectedBy: string;
  restaurants?: Restaurant;
  reviews?: Array<Review>;
  settlementsBreakup?: Array<SettlementsBreakup>;
  totalAmount: Decimal | null;
  updatedAt: Date | null;
};
