import { AddressWhereUniqueInput } from "../address/AddressWhereUniqueInput";
import { AppUserWhereUniqueInput } from "../appUser/AppUserWhereUniqueInput";
import { CouponWhereUniqueInput } from "../coupon/CouponWhereUniqueInput";
import { Decimal } from "decimal.js";
import { FulfillmentBookUpdateManyWithoutOrderHistoriesInput } from "./FulfillmentBookUpdateManyWithoutOrderHistoriesInput";
import { OrderItemUpdateManyWithoutOrderHistoriesInput } from "./OrderItemUpdateManyWithoutOrderHistoriesInput";
import { OrdersHashtagsMapUpdateManyWithoutOrderHistoriesInput } from "./OrdersHashtagsMapUpdateManyWithoutOrderHistoriesInput";
import { PaymentMethodWhereUniqueInput } from "../paymentMethod/PaymentMethodWhereUniqueInput";
import { PaymentsBookUpdateManyWithoutOrderHistoriesInput } from "./PaymentsBookUpdateManyWithoutOrderHistoriesInput";
import { RatingUpdateManyWithoutOrderHistoriesInput } from "./RatingUpdateManyWithoutOrderHistoriesInput";
import { RestaurantWhereUniqueInput } from "../restaurant/RestaurantWhereUniqueInput";
import { ReviewUpdateManyWithoutOrderHistoriesInput } from "./ReviewUpdateManyWithoutOrderHistoriesInput";
import { SettlementsBreakupUpdateManyWithoutOrderHistoriesInput } from "./SettlementsBreakupUpdateManyWithoutOrderHistoriesInput";

export type OrderHistoryUpdateInput = {
  addresses?: AddressWhereUniqueInput;
  appUsers?: AppUserWhereUniqueInput;
  coupons?: CouponWhereUniqueInput;
  deliveryTipsAmount?: Decimal | null;
  discountAmount?: Decimal | null;
  estimatedDeliveryTime?: Date | null;
  finalAmount?: Decimal | null;
  fulfillmentBook?: FulfillmentBookUpdateManyWithoutOrderHistoriesInput;
  isCancelled?: boolean | null;
  isFulfilled?: boolean | null;
  isPaid?: boolean | null;
  isRejected?: boolean | null;
  orderIdRef?: number;
  orderItems?: OrderItemUpdateManyWithoutOrderHistoriesInput;
  ordersHashtagsMap?: OrdersHashtagsMapUpdateManyWithoutOrderHistoriesInput;
  order_type?: "Delivery" | "TakeAway" | "DineIn" | null;
  packagingAmount?: Decimal | null;
  paymentMethods?: PaymentMethodWhereUniqueInput;
  paymentsBook?: PaymentsBookUpdateManyWithoutOrderHistoriesInput;
  preparationInstruction?: string | null;
  preparationTime?: number | null;
  ratings?: RatingUpdateManyWithoutOrderHistoriesInput;
  rejectedBy?: string;
  restaurants?: RestaurantWhereUniqueInput;
  reviews?: ReviewUpdateManyWithoutOrderHistoriesInput;
  settlementsBreakup?: SettlementsBreakupUpdateManyWithoutOrderHistoriesInput;
  totalAmount?: Decimal | null;
  updatedAt?: Date | null;
};
