import { AddressWhereUniqueInput } from "../address/AddressWhereUniqueInput";
import { AppUserWhereUniqueInput } from "../appUser/AppUserWhereUniqueInput";
import { CouponWhereUniqueInput } from "../coupon/CouponWhereUniqueInput";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { DecimalNullableFilter } from "../../util/DecimalNullableFilter";
import { FulfillmentBookListRelationFilter } from "../fulfillmentBook/FulfillmentBookListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { IntFilter } from "../../util/IntFilter";
import { OrderItemListRelationFilter } from "../orderItem/OrderItemListRelationFilter";
import { OrdersHashtagsMapListRelationFilter } from "../ordersHashtagsMap/OrdersHashtagsMapListRelationFilter";
import { PaymentMethodWhereUniqueInput } from "../paymentMethod/PaymentMethodWhereUniqueInput";
import { PaymentsBookListRelationFilter } from "../paymentsBook/PaymentsBookListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { RatingListRelationFilter } from "../rating/RatingListRelationFilter";
import { RestaurantWhereUniqueInput } from "../restaurant/RestaurantWhereUniqueInput";
import { ReviewListRelationFilter } from "../review/ReviewListRelationFilter";
import { SettlementsBreakupListRelationFilter } from "../settlementsBreakup/SettlementsBreakupListRelationFilter";

export type OrderHistoryWhereInput = {
  addresses?: AddressWhereUniqueInput;
  appUsers?: AppUserWhereUniqueInput;
  coupons?: CouponWhereUniqueInput;
  createdAt?: DateTimeNullableFilter;
  deliveryTipsAmount?: DecimalNullableFilter;
  discountAmount?: DecimalNullableFilter;
  estimatedDeliveryTime?: DateTimeNullableFilter;
  finalAmount?: DecimalNullableFilter;
  fulfillmentBook?: FulfillmentBookListRelationFilter;
  id?: StringFilter;
  isCancelled?: BooleanNullableFilter;
  isFulfilled?: BooleanNullableFilter;
  isPaid?: BooleanNullableFilter;
  isRejected?: BooleanNullableFilter;
  orderDateTime?: DateTimeNullableFilter;
  orderIdRef?: IntFilter;
  orderItems?: OrderItemListRelationFilter;
  ordersHashtagsMap?: OrdersHashtagsMapListRelationFilter;
  order_type?: "Delivery" | "TakeAway" | "DineIn";
  packagingAmount?: DecimalNullableFilter;
  paymentMethods?: PaymentMethodWhereUniqueInput;
  paymentsBook?: PaymentsBookListRelationFilter;
  preparationInstruction?: StringNullableFilter;
  preparationTime?: IntNullableFilter;
  ratings?: RatingListRelationFilter;
  rejectedBy?: StringFilter;
  restaurants?: RestaurantWhereUniqueInput;
  reviews?: ReviewListRelationFilter;
  settlementsBreakup?: SettlementsBreakupListRelationFilter;
  totalAmount?: DecimalNullableFilter;
  updatedAt?: DateTimeNullableFilter;
};
