import { AddressWhereUniqueInput } from "../address/AddressWhereUniqueInput";
import { AppUserWhereUniqueInput } from "../appUser/AppUserWhereUniqueInput";
import { CouponWhereUniqueInput } from "../coupon/CouponWhereUniqueInput";
import { Decimal } from "decimal.js";
import { FulfillmentBookCreateNestedManyWithoutOrderHistoriesInput } from "./FulfillmentBookCreateNestedManyWithoutOrderHistoriesInput";
import { OrderItemCreateNestedManyWithoutOrderHistoriesInput } from "./OrderItemCreateNestedManyWithoutOrderHistoriesInput";
import { OrdersHashtagsMapCreateNestedManyWithoutOrderHistoriesInput } from "./OrdersHashtagsMapCreateNestedManyWithoutOrderHistoriesInput";
import { PaymentMethodWhereUniqueInput } from "../paymentMethod/PaymentMethodWhereUniqueInput";
import { PaymentsBookCreateNestedManyWithoutOrderHistoriesInput } from "./PaymentsBookCreateNestedManyWithoutOrderHistoriesInput";
import { RatingCreateNestedManyWithoutOrderHistoriesInput } from "./RatingCreateNestedManyWithoutOrderHistoriesInput";
import { RestaurantWhereUniqueInput } from "../restaurant/RestaurantWhereUniqueInput";
import { ReviewCreateNestedManyWithoutOrderHistoriesInput } from "./ReviewCreateNestedManyWithoutOrderHistoriesInput";
import { SettlementsBreakupCreateNestedManyWithoutOrderHistoriesInput } from "./SettlementsBreakupCreateNestedManyWithoutOrderHistoriesInput";

export type OrderHistoryCreateInput = {
  addresses: AddressWhereUniqueInput;
  appUsers: AppUserWhereUniqueInput;
  coupons: CouponWhereUniqueInput;
  deliveryTipsAmount?: Decimal | null;
  discountAmount?: Decimal | null;
  estimatedDeliveryTime?: Date | null;
  finalAmount?: Decimal | null;
  fulfillmentBook?: FulfillmentBookCreateNestedManyWithoutOrderHistoriesInput;
  isCancelled?: boolean | null;
  isFulfilled?: boolean | null;
  isPaid?: boolean | null;
  isRejected?: boolean | null;
  orderIdRef: number;
  orderItems?: OrderItemCreateNestedManyWithoutOrderHistoriesInput;
  ordersHashtagsMap?: OrdersHashtagsMapCreateNestedManyWithoutOrderHistoriesInput;
  order_type?: "Delivery" | "TakeAway" | "DineIn" | null;
  packagingAmount?: Decimal | null;
  paymentMethods: PaymentMethodWhereUniqueInput;
  paymentsBook?: PaymentsBookCreateNestedManyWithoutOrderHistoriesInput;
  preparationInstruction?: string | null;
  preparationTime?: number | null;
  ratings?: RatingCreateNestedManyWithoutOrderHistoriesInput;
  rejectedBy: string;
  restaurants: RestaurantWhereUniqueInput;
  reviews?: ReviewCreateNestedManyWithoutOrderHistoriesInput;
  settlementsBreakup?: SettlementsBreakupCreateNestedManyWithoutOrderHistoriesInput;
  totalAmount?: Decimal | null;
  updatedAt?: Date | null;
};
