/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ErrorLog } from "./ErrorLog";
import { ErrorLogCountArgs } from "./ErrorLogCountArgs";
import { ErrorLogFindManyArgs } from "./ErrorLogFindManyArgs";
import { ErrorLogFindUniqueArgs } from "./ErrorLogFindUniqueArgs";
import { CreateErrorLogArgs } from "./CreateErrorLogArgs";
import { UpdateErrorLogArgs } from "./UpdateErrorLogArgs";
import { DeleteErrorLogArgs } from "./DeleteErrorLogArgs";
import { AppUser } from "../../appUser/base/AppUser";
import { ErrorLogService } from "../errorLog.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ErrorLog)
export class ErrorLogResolverBase {
  constructor(
    protected readonly service: ErrorLogService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ErrorLog",
    action: "read",
    possession: "any",
  })
  async _errorLogsMeta(
    @graphql.Args() args: ErrorLogCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ErrorLog])
  @nestAccessControl.UseRoles({
    resource: "ErrorLog",
    action: "read",
    possession: "any",
  })
  async errorLogs(
    @graphql.Args() args: ErrorLogFindManyArgs
  ): Promise<ErrorLog[]> {
    return this.service.errorLogs(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ErrorLog, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ErrorLog",
    action: "read",
    possession: "own",
  })
  async errorLog(
    @graphql.Args() args: ErrorLogFindUniqueArgs
  ): Promise<ErrorLog | null> {
    const result = await this.service.errorLog(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ErrorLog)
  @nestAccessControl.UseRoles({
    resource: "ErrorLog",
    action: "create",
    possession: "any",
  })
  async createErrorLog(
    @graphql.Args() args: CreateErrorLogArgs
  ): Promise<ErrorLog> {
    return await this.service.createErrorLog({
      ...args,
      data: {
        ...args.data,

        appUsers: {
          connect: args.data.appUsers,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ErrorLog)
  @nestAccessControl.UseRoles({
    resource: "ErrorLog",
    action: "update",
    possession: "any",
  })
  async updateErrorLog(
    @graphql.Args() args: UpdateErrorLogArgs
  ): Promise<ErrorLog | null> {
    try {
      return await this.service.updateErrorLog({
        ...args,
        data: {
          ...args.data,

          appUsers: {
            connect: args.data.appUsers,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ErrorLog)
  @nestAccessControl.UseRoles({
    resource: "ErrorLog",
    action: "delete",
    possession: "any",
  })
  async deleteErrorLog(
    @graphql.Args() args: DeleteErrorLogArgs
  ): Promise<ErrorLog | null> {
    try {
      return await this.service.deleteErrorLog(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => AppUser, {
    nullable: true,
    name: "appUsers",
  })
  @nestAccessControl.UseRoles({
    resource: "AppUser",
    action: "read",
    possession: "any",
  })
  async getAppUsers(
    @graphql.Parent() parent: ErrorLog
  ): Promise<AppUser | null> {
    const result = await this.service.getAppUsers(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
