import { Decimal } from "decimal.js";
import { AppUser } from "../appUser/AppUser";
import { OrderHistory } from "../orderHistory/OrderHistory";
import { PayoutCycle } from "../payoutCycle/PayoutCycle";

export type SettlementsBreakup = {
  amountForGstUnder95: Decimal | null;
  amountForTcs: Decimal | null;
  appUsers?: AppUser;
  bankUtr: string | null;
  baseServiceFee: Decimal | null;
  baseServiceFeePercentage: Decimal | null;
  businessname: string | null;
  cancellationOrRejectionReason: string | null;
  cancellationOrRejectionState: string | null;
  cancellationPolicy: string | null;
  cashReceivedSelfDelivery: Decimal | null;
  commissionableAmount: Decimal | null;
  createdAt: Date | null;
  creditDebitNoteAdjustment: Decimal | null;
  customerCompensation: Decimal | null;
  customerPayable: Decimal | null;
  deliveryCharge: Decimal | null;
  deliveryChargesRecovery: Decimal | null;
  deliveryStateCode: string | null;
  discountConstruct: string | null;
  extraInventoryAds: Decimal | null;
  fulfilmentFee: Decimal | null;
  fulfilmentFeePerKm: Decimal | null;
  gstPaidByPlatform: Decimal | null;
  gstToBePaidByRestaurant: Decimal | null;
  id: string;
  netAdditions: Decimal | null;
  netDeductions: Decimal | null;
  orderDateTime: Date | null;
  orderDistanceKm: Decimal | null;
  orderHistory?: OrderHistory;
  orderLevelPayout: Decimal | null;
  orderStatus: string | null;
  orderType: string | null;
  packagingCharge: Decimal | null;
  paymentMechanismFee: Decimal | null;
  paymentMode: string | null;
  payoutCycles?: PayoutCycle;
  promoRecoveryAdjustment: Decimal | null;
  restaurantDiscountFromOthers: Decimal | null;
  restaurantDiscountFromPromo: Decimal | null;
  restaurantId: string;
  settlementDate: Date | null;
  settlementStatus: string | null;
  subtotal: Decimal | null;
  taxCollectedAtSource: Decimal | null;
  taxesOnServicePaymentFees: Decimal | null;
  tcsIgstAmount: Decimal | null;
  tds194OAmount: Decimal | null;
  totalGstFromCustomers: Decimal | null;
  unsettledAmount: Decimal | null;
  updatedAt: Date | null;
  weekNo: number | null;
};
