/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TaxRateInformationService } from "../taxRateInformation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TaxRateInformationCreateInput } from "./TaxRateInformationCreateInput";
import { TaxRateInformation } from "./TaxRateInformation";
import { TaxRateInformationFindManyArgs } from "./TaxRateInformationFindManyArgs";
import { TaxRateInformationWhereUniqueInput } from "./TaxRateInformationWhereUniqueInput";
import { TaxRateInformationUpdateInput } from "./TaxRateInformationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TaxRateInformationControllerBase {
  constructor(
    protected readonly service: TaxRateInformationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TaxRateInformation })
  @nestAccessControl.UseRoles({
    resource: "TaxRateInformation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTaxRateInformation(
    @common.Body() data: TaxRateInformationCreateInput
  ): Promise<TaxRateInformation> {
    return await this.service.createTaxRateInformation({
      data: {
        ...data,

        restaurants: {
          connect: data.restaurants,
        },
      },
      select: {
        cgstRate: true,
        createdAt: true,
        id: true,
        netTaxTransferrable: true,

        restaurants: {
          select: {
            id: true,
          },
        },

        sgstRate: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TaxRateInformation] })
  @ApiNestedQuery(TaxRateInformationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TaxRateInformation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async taxRateInformations(
    @common.Req() request: Request
  ): Promise<TaxRateInformation[]> {
    const args = plainToClass(TaxRateInformationFindManyArgs, request.query);
    return this.service.taxRateInformations({
      ...args,
      select: {
        cgstRate: true,
        createdAt: true,
        id: true,
        netTaxTransferrable: true,

        restaurants: {
          select: {
            id: true,
          },
        },

        sgstRate: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TaxRateInformation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TaxRateInformation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async taxRateInformation(
    @common.Param() params: TaxRateInformationWhereUniqueInput
  ): Promise<TaxRateInformation | null> {
    const result = await this.service.taxRateInformation({
      where: params,
      select: {
        cgstRate: true,
        createdAt: true,
        id: true,
        netTaxTransferrable: true,

        restaurants: {
          select: {
            id: true,
          },
        },

        sgstRate: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TaxRateInformation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TaxRateInformation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTaxRateInformation(
    @common.Param() params: TaxRateInformationWhereUniqueInput,
    @common.Body() data: TaxRateInformationUpdateInput
  ): Promise<TaxRateInformation | null> {
    try {
      return await this.service.updateTaxRateInformation({
        where: params,
        data: {
          ...data,

          restaurants: {
            connect: data.restaurants,
          },
        },
        select: {
          cgstRate: true,
          createdAt: true,
          id: true,
          netTaxTransferrable: true,

          restaurants: {
            select: {
              id: true,
            },
          },

          sgstRate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TaxRateInformation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TaxRateInformation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTaxRateInformation(
    @common.Param() params: TaxRateInformationWhereUniqueInput
  ): Promise<TaxRateInformation | null> {
    try {
      return await this.service.deleteTaxRateInformation({
        where: params,
        select: {
          cgstRate: true,
          createdAt: true,
          id: true,
          netTaxTransferrable: true,

          restaurants: {
            select: {
              id: true,
            },
          },

          sgstRate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
