/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ComboItemWindowMapCreateNestedManyWithoutTimeWindowsInput } from "./ComboItemWindowMapCreateNestedManyWithoutTimeWindowsInput";
import { ValidateNested, IsOptional, IsDate } from "class-validator";
import { Type } from "class-transformer";
import { DiscountWindowMapCreateNestedManyWithoutTimeWindowsInput } from "./DiscountWindowMapCreateNestedManyWithoutTimeWindowsInput";
import { MenuItemsWindowMapCreateNestedManyWithoutTimeWindowsInput } from "./MenuItemsWindowMapCreateNestedManyWithoutTimeWindowsInput";
import { RestaurantTimeWindowMapCreateNestedManyWithoutTimeWindowsInput } from "./RestaurantTimeWindowMapCreateNestedManyWithoutTimeWindowsInput";

@InputType()
class TimeWindowCreateInput {
  @ApiProperty({
    required: false,
    type: () => ComboItemWindowMapCreateNestedManyWithoutTimeWindowsInput,
  })
  @ValidateNested()
  @Type(() => ComboItemWindowMapCreateNestedManyWithoutTimeWindowsInput)
  @IsOptional()
  @Field(() => ComboItemWindowMapCreateNestedManyWithoutTimeWindowsInput, {
    nullable: true,
  })
  comboItemWindowMap?: ComboItemWindowMapCreateNestedManyWithoutTimeWindowsInput;

  @ApiProperty({
    required: false,
    type: () => DiscountWindowMapCreateNestedManyWithoutTimeWindowsInput,
  })
  @ValidateNested()
  @Type(() => DiscountWindowMapCreateNestedManyWithoutTimeWindowsInput)
  @IsOptional()
  @Field(() => DiscountWindowMapCreateNestedManyWithoutTimeWindowsInput, {
    nullable: true,
  })
  discountWindowMap?: DiscountWindowMapCreateNestedManyWithoutTimeWindowsInput;

  @ApiProperty({
    required: false,
    type: () => MenuItemsWindowMapCreateNestedManyWithoutTimeWindowsInput,
  })
  @ValidateNested()
  @Type(() => MenuItemsWindowMapCreateNestedManyWithoutTimeWindowsInput)
  @IsOptional()
  @Field(() => MenuItemsWindowMapCreateNestedManyWithoutTimeWindowsInput, {
    nullable: true,
  })
  menuItemsWindowMap?: MenuItemsWindowMapCreateNestedManyWithoutTimeWindowsInput;

  @ApiProperty({
    required: false,
    type: () => RestaurantTimeWindowMapCreateNestedManyWithoutTimeWindowsInput,
  })
  @ValidateNested()
  @Type(() => RestaurantTimeWindowMapCreateNestedManyWithoutTimeWindowsInput)
  @IsOptional()
  @Field(() => RestaurantTimeWindowMapCreateNestedManyWithoutTimeWindowsInput, {
    nullable: true,
  })
  restaurantTimeWindowMap?: RestaurantTimeWindowMapCreateNestedManyWithoutTimeWindowsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  windowEnd?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  windowStart?: Date | null;
}

export { TimeWindowCreateInput as TimeWindowCreateInput };
