/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ComboItemWindowMapUpdateManyWithoutTimeWindowsInput } from "./ComboItemWindowMapUpdateManyWithoutTimeWindowsInput";
import { ValidateNested, IsOptional, IsDate } from "class-validator";
import { Type } from "class-transformer";
import { DiscountWindowMapUpdateManyWithoutTimeWindowsInput } from "./DiscountWindowMapUpdateManyWithoutTimeWindowsInput";
import { MenuItemsWindowMapUpdateManyWithoutTimeWindowsInput } from "./MenuItemsWindowMapUpdateManyWithoutTimeWindowsInput";
import { RestaurantTimeWindowMapUpdateManyWithoutTimeWindowsInput } from "./RestaurantTimeWindowMapUpdateManyWithoutTimeWindowsInput";

@InputType()
class TimeWindowUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ComboItemWindowMapUpdateManyWithoutTimeWindowsInput,
  })
  @ValidateNested()
  @Type(() => ComboItemWindowMapUpdateManyWithoutTimeWindowsInput)
  @IsOptional()
  @Field(() => ComboItemWindowMapUpdateManyWithoutTimeWindowsInput, {
    nullable: true,
  })
  comboItemWindowMap?: ComboItemWindowMapUpdateManyWithoutTimeWindowsInput;

  @ApiProperty({
    required: false,
    type: () => DiscountWindowMapUpdateManyWithoutTimeWindowsInput,
  })
  @ValidateNested()
  @Type(() => DiscountWindowMapUpdateManyWithoutTimeWindowsInput)
  @IsOptional()
  @Field(() => DiscountWindowMapUpdateManyWithoutTimeWindowsInput, {
    nullable: true,
  })
  discountWindowMap?: DiscountWindowMapUpdateManyWithoutTimeWindowsInput;

  @ApiProperty({
    required: false,
    type: () => MenuItemsWindowMapUpdateManyWithoutTimeWindowsInput,
  })
  @ValidateNested()
  @Type(() => MenuItemsWindowMapUpdateManyWithoutTimeWindowsInput)
  @IsOptional()
  @Field(() => MenuItemsWindowMapUpdateManyWithoutTimeWindowsInput, {
    nullable: true,
  })
  menuItemsWindowMap?: MenuItemsWindowMapUpdateManyWithoutTimeWindowsInput;

  @ApiProperty({
    required: false,
    type: () => RestaurantTimeWindowMapUpdateManyWithoutTimeWindowsInput,
  })
  @ValidateNested()
  @Type(() => RestaurantTimeWindowMapUpdateManyWithoutTimeWindowsInput)
  @IsOptional()
  @Field(() => RestaurantTimeWindowMapUpdateManyWithoutTimeWindowsInput, {
    nullable: true,
  })
  restaurantTimeWindowMap?: RestaurantTimeWindowMapUpdateManyWithoutTimeWindowsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  windowEnd?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  windowStart?: Date | null;
}

export { TimeWindowUpdateInput as TimeWindowUpdateInput };
