import { AccessLogUpdateManyWithoutAppUsersInput } from "./AccessLogUpdateManyWithoutAppUsersInput";
import { CouponRedemptionUpdateManyWithoutAppUsersInput } from "./CouponRedemptionUpdateManyWithoutAppUsersInput";
import { CustomerPreferenceUpdateManyWithoutAppUsersInput } from "./CustomerPreferenceUpdateManyWithoutAppUsersInput";
import { CustomerSubscriptionUpdateManyWithoutAppUsersInput } from "./CustomerSubscriptionUpdateManyWithoutAppUsersInput";
import { ErrorLogUpdateManyWithoutAppUsersInput } from "./ErrorLogUpdateManyWithoutAppUsersInput";
import { FavouriteUpdateManyWithoutAppUsersInput } from "./FavouriteUpdateManyWithoutAppUsersInput";
import { NotificationUpdateManyWithoutAppUsersInput } from "./NotificationUpdateManyWithoutAppUsersInput";
import { NotificationSettingUpdateManyWithoutAppUsersInput } from "./NotificationSettingUpdateManyWithoutAppUsersInput";
import { OrderHistoryUpdateManyWithoutAppUsersInput } from "./OrderHistoryUpdateManyWithoutAppUsersInput";
import { ReportUpdateManyWithoutAppUsersInput } from "./ReportUpdateManyWithoutAppUsersInput";
import { ReservationUpdateManyWithoutAppUsersInput } from "./ReservationUpdateManyWithoutAppUsersInput";
import { RewardUpdateManyWithoutAppUsersInput } from "./RewardUpdateManyWithoutAppUsersInput";
import { SettlementsBreakupUpdateManyWithoutAppUsersInput } from "./SettlementsBreakupUpdateManyWithoutAppUsersInput";
import { SsoLookupUpdateManyWithoutAppUsersInput } from "./SsoLookupUpdateManyWithoutAppUsersInput";
import { SubscriptionUpdateManyWithoutAppUsersInput } from "./SubscriptionUpdateManyWithoutAppUsersInput";
import { UserCustomerLookupUpdateManyWithoutAppUsersInput } from "./UserCustomerLookupUpdateManyWithoutAppUsersInput";
import { UserFeedbackUpdateManyWithoutAppUsersInput } from "./UserFeedbackUpdateManyWithoutAppUsersInput";
import { UsersHashtagsMapUpdateManyWithoutAppUsersInput } from "./UsersHashtagsMapUpdateManyWithoutAppUsersInput";

export type AppUserUpdateInput = {
  accessLogs?: AccessLogUpdateManyWithoutAppUsersInput;
  account_status?: "Live" | "Is_Disabled" | "Is_Deleted" | null;
  couponRedemptions?: CouponRedemptionUpdateManyWithoutAppUsersInput;
  customerPreferences?: CustomerPreferenceUpdateManyWithoutAppUsersInput;
  customerSubscriptions?: CustomerSubscriptionUpdateManyWithoutAppUsersInput;
  errorLogs?: ErrorLogUpdateManyWithoutAppUsersInput;
  favourites?: FavouriteUpdateManyWithoutAppUsersInput;
  notifications?: NotificationUpdateManyWithoutAppUsersInput;
  notificationSettings?: NotificationSettingUpdateManyWithoutAppUsersInput;
  orderHistory?: OrderHistoryUpdateManyWithoutAppUsersInput;
  profilePicUrl?: string | null;
  reports?: ReportUpdateManyWithoutAppUsersInput;
  reservations?: ReservationUpdateManyWithoutAppUsersInput;
  rewards?: RewardUpdateManyWithoutAppUsersInput;
  settlementsBreakup?: SettlementsBreakupUpdateManyWithoutAppUsersInput;
  ssoLookup?: SsoLookupUpdateManyWithoutAppUsersInput;
  subscriptions?: SubscriptionUpdateManyWithoutAppUsersInput;
  updatedAt?: Date | null;
  userCustomerLookup?: UserCustomerLookupUpdateManyWithoutAppUsersInput;
  userFeedbacks?: UserFeedbackUpdateManyWithoutAppUsersInput;
  usersHashtagsMap?: UsersHashtagsMapUpdateManyWithoutAppUsersInput;
};
