import { AccessLogCreateNestedManyWithoutAppUsersInput } from "./AccessLogCreateNestedManyWithoutAppUsersInput";
import { CouponRedemptionCreateNestedManyWithoutAppUsersInput } from "./CouponRedemptionCreateNestedManyWithoutAppUsersInput";
import { CustomerPreferenceCreateNestedManyWithoutAppUsersInput } from "./CustomerPreferenceCreateNestedManyWithoutAppUsersInput";
import { CustomerSubscriptionCreateNestedManyWithoutAppUsersInput } from "./CustomerSubscriptionCreateNestedManyWithoutAppUsersInput";
import { ErrorLogCreateNestedManyWithoutAppUsersInput } from "./ErrorLogCreateNestedManyWithoutAppUsersInput";
import { FavouriteCreateNestedManyWithoutAppUsersInput } from "./FavouriteCreateNestedManyWithoutAppUsersInput";
import { NotificationCreateNestedManyWithoutAppUsersInput } from "./NotificationCreateNestedManyWithoutAppUsersInput";
import { NotificationSettingCreateNestedManyWithoutAppUsersInput } from "./NotificationSettingCreateNestedManyWithoutAppUsersInput";
import { OrderHistoryCreateNestedManyWithoutAppUsersInput } from "./OrderHistoryCreateNestedManyWithoutAppUsersInput";
import { ReportCreateNestedManyWithoutAppUsersInput } from "./ReportCreateNestedManyWithoutAppUsersInput";
import { ReservationCreateNestedManyWithoutAppUsersInput } from "./ReservationCreateNestedManyWithoutAppUsersInput";
import { RewardCreateNestedManyWithoutAppUsersInput } from "./RewardCreateNestedManyWithoutAppUsersInput";
import { SettlementsBreakupCreateNestedManyWithoutAppUsersInput } from "./SettlementsBreakupCreateNestedManyWithoutAppUsersInput";
import { SsoLookupCreateNestedManyWithoutAppUsersInput } from "./SsoLookupCreateNestedManyWithoutAppUsersInput";
import { SubscriptionCreateNestedManyWithoutAppUsersInput } from "./SubscriptionCreateNestedManyWithoutAppUsersInput";
import { UserCustomerLookupCreateNestedManyWithoutAppUsersInput } from "./UserCustomerLookupCreateNestedManyWithoutAppUsersInput";
import { UserFeedbackCreateNestedManyWithoutAppUsersInput } from "./UserFeedbackCreateNestedManyWithoutAppUsersInput";
import { UsersHashtagsMapCreateNestedManyWithoutAppUsersInput } from "./UsersHashtagsMapCreateNestedManyWithoutAppUsersInput";

export type AppUserCreateInput = {
  accessLogs?: AccessLogCreateNestedManyWithoutAppUsersInput;
  account_status?: "Live" | "Is_Disabled" | "Is_Deleted" | null;
  couponRedemptions?: CouponRedemptionCreateNestedManyWithoutAppUsersInput;
  customerPreferences?: CustomerPreferenceCreateNestedManyWithoutAppUsersInput;
  customerSubscriptions?: CustomerSubscriptionCreateNestedManyWithoutAppUsersInput;
  errorLogs?: ErrorLogCreateNestedManyWithoutAppUsersInput;
  favourites?: FavouriteCreateNestedManyWithoutAppUsersInput;
  notifications?: NotificationCreateNestedManyWithoutAppUsersInput;
  notificationSettings?: NotificationSettingCreateNestedManyWithoutAppUsersInput;
  orderHistory?: OrderHistoryCreateNestedManyWithoutAppUsersInput;
  profilePicUrl?: string | null;
  reports?: ReportCreateNestedManyWithoutAppUsersInput;
  reservations?: ReservationCreateNestedManyWithoutAppUsersInput;
  rewards?: RewardCreateNestedManyWithoutAppUsersInput;
  settlementsBreakup?: SettlementsBreakupCreateNestedManyWithoutAppUsersInput;
  ssoLookup?: SsoLookupCreateNestedManyWithoutAppUsersInput;
  subscriptions?: SubscriptionCreateNestedManyWithoutAppUsersInput;
  updatedAt?: Date | null;
  userCustomerLookup?: UserCustomerLookupCreateNestedManyWithoutAppUsersInput;
  userFeedbacks?: UserFeedbackCreateNestedManyWithoutAppUsersInput;
  usersHashtagsMap?: UsersHashtagsMapCreateNestedManyWithoutAppUsersInput;
};
