import { AccessLogListRelationFilter } from "../accessLog/AccessLogListRelationFilter";
import { CouponRedemptionListRelationFilter } from "../couponRedemption/CouponRedemptionListRelationFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { CustomerPreferenceListRelationFilter } from "../customerPreference/CustomerPreferenceListRelationFilter";
import { CustomerSubscriptionListRelationFilter } from "../customerSubscription/CustomerSubscriptionListRelationFilter";
import { ErrorLogListRelationFilter } from "../errorLog/ErrorLogListRelationFilter";
import { FavouriteListRelationFilter } from "../favourite/FavouriteListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { NotificationListRelationFilter } from "../notification/NotificationListRelationFilter";
import { NotificationSettingListRelationFilter } from "../notificationSetting/NotificationSettingListRelationFilter";
import { OrderHistoryListRelationFilter } from "../orderHistory/OrderHistoryListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { ReportListRelationFilter } from "../report/ReportListRelationFilter";
import { ReservationListRelationFilter } from "../reservation/ReservationListRelationFilter";
import { RewardListRelationFilter } from "../reward/RewardListRelationFilter";
import { SettlementsBreakupListRelationFilter } from "../settlementsBreakup/SettlementsBreakupListRelationFilter";
import { SsoLookupListRelationFilter } from "../ssoLookup/SsoLookupListRelationFilter";
import { SubscriptionListRelationFilter } from "../subscription/SubscriptionListRelationFilter";
import { UserCustomerLookupListRelationFilter } from "../userCustomerLookup/UserCustomerLookupListRelationFilter";
import { UserFeedbackListRelationFilter } from "../userFeedback/UserFeedbackListRelationFilter";
import { UsersHashtagsMapListRelationFilter } from "../usersHashtagsMap/UsersHashtagsMapListRelationFilter";

export type AppUserWhereInput = {
  accessLogs?: AccessLogListRelationFilter;
  account_status?: "Live" | "Is_Disabled" | "Is_Deleted";
  couponRedemptions?: CouponRedemptionListRelationFilter;
  createdAt?: DateTimeNullableFilter;
  customerPreferences?: CustomerPreferenceListRelationFilter;
  customerSubscriptions?: CustomerSubscriptionListRelationFilter;
  errorLogs?: ErrorLogListRelationFilter;
  favourites?: FavouriteListRelationFilter;
  id?: StringFilter;
  notifications?: NotificationListRelationFilter;
  notificationSettings?: NotificationSettingListRelationFilter;
  orderHistory?: OrderHistoryListRelationFilter;
  profilePicUrl?: StringNullableFilter;
  reports?: ReportListRelationFilter;
  reservations?: ReservationListRelationFilter;
  rewards?: RewardListRelationFilter;
  settlementsBreakup?: SettlementsBreakupListRelationFilter;
  ssoLookup?: SsoLookupListRelationFilter;
  subscriptions?: SubscriptionListRelationFilter;
  updatedAt?: DateTimeNullableFilter;
  userCustomerLookup?: UserCustomerLookupListRelationFilter;
  userFeedbacks?: UserFeedbackListRelationFilter;
  usersHashtagsMap?: UsersHashtagsMapListRelationFilter;
};
