/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AppUserWhereUniqueInput } from "../../appUser/base/AppUserWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { FavouriteMenuItemListRelationFilter } from "../../favouriteMenuItem/base/FavouriteMenuItemListRelationFilter";
import { FavouriteRestaurantListRelationFilter } from "../../favouriteRestaurant/base/FavouriteRestaurantListRelationFilter";
import { StringFilter } from "../../util/StringFilter";

@InputType()
class FavouriteWhereInput {
  @ApiProperty({
    required: false,
    type: () => AppUserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AppUserWhereUniqueInput)
  @IsOptional()
  @Field(() => AppUserWhereUniqueInput, {
    nullable: true,
  })
  appUsers?: AppUserWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  createdAt?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: () => FavouriteMenuItemListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FavouriteMenuItemListRelationFilter)
  @IsOptional()
  @Field(() => FavouriteMenuItemListRelationFilter, {
    nullable: true,
  })
  favouriteMenuItems?: FavouriteMenuItemListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => FavouriteRestaurantListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FavouriteRestaurantListRelationFilter)
  @IsOptional()
  @Field(() => FavouriteRestaurantListRelationFilter, {
    nullable: true,
  })
  favouriteRestaurant?: FavouriteRestaurantListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  updatedAt?: DateTimeNullableFilter;
}

export { FavouriteWhereInput as FavouriteWhereInput };
