/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field, Float } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  IsNumber,
  IsBoolean,
  ValidateNested,
  IsDate,
} from "class-validator";
import { Decimal } from "decimal.js";
import { OptionsAddonsGroupWhereUniqueInput } from "../../optionsAddonsGroup/base/OptionsAddonsGroupWhereUniqueInput";
import { Type } from "class-transformer";
import { OrderItemsAddonCreateNestedManyWithoutOptionsAddOnsItemsInput } from "./OrderItemsAddonCreateNestedManyWithoutOptionsAddOnsItemsInput";

@InputType()
class OptionsAddOnsItemCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  addOnName?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Float, {
    nullable: true,
  })
  addOnPrice?: Decimal | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  addonsImageUrl?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  containsEgg?: boolean | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isVegetarian?: boolean | null;

  @ApiProperty({
    required: true,
    type: () => OptionsAddonsGroupWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => OptionsAddonsGroupWhereUniqueInput)
  @Field(() => OptionsAddonsGroupWhereUniqueInput)
  optionsAddonsGroup!: OptionsAddonsGroupWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => OrderItemsAddonCreateNestedManyWithoutOptionsAddOnsItemsInput,
  })
  @ValidateNested()
  @Type(() => OrderItemsAddonCreateNestedManyWithoutOptionsAddOnsItemsInput)
  @IsOptional()
  @Field(() => OrderItemsAddonCreateNestedManyWithoutOptionsAddOnsItemsInput, {
    nullable: true,
  })
  orderItemsAddons?: OrderItemsAddonCreateNestedManyWithoutOptionsAddOnsItemsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  updatedAt?: Date | null;
}

export { OptionsAddOnsItemCreateInput as OptionsAddOnsItemCreateInput };
