/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MenuItemIngredientService } from "../menuItemIngredient.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MenuItemIngredientCreateInput } from "./MenuItemIngredientCreateInput";
import { MenuItemIngredient } from "./MenuItemIngredient";
import { MenuItemIngredientFindManyArgs } from "./MenuItemIngredientFindManyArgs";
import { MenuItemIngredientWhereUniqueInput } from "./MenuItemIngredientWhereUniqueInput";
import { MenuItemIngredientUpdateInput } from "./MenuItemIngredientUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MenuItemIngredientControllerBase {
  constructor(
    protected readonly service: MenuItemIngredientService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MenuItemIngredient })
  @nestAccessControl.UseRoles({
    resource: "MenuItemIngredient",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMenuItemIngredient(
    @common.Body() data: MenuItemIngredientCreateInput
  ): Promise<MenuItemIngredient> {
    return await this.service.createMenuItemIngredient({
      data: {
        ...data,

        menuItems: {
          connect: data.menuItems,
        },
      },
      select: {
        createdAt: true,
        id: true,
        ingredient: true,

        menuItems: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [MenuItemIngredient] })
  @ApiNestedQuery(MenuItemIngredientFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "MenuItemIngredient",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async menuItemIngredients(
    @common.Req() request: Request
  ): Promise<MenuItemIngredient[]> {
    const args = plainToClass(MenuItemIngredientFindManyArgs, request.query);
    return this.service.menuItemIngredients({
      ...args,
      select: {
        createdAt: true,
        id: true,
        ingredient: true,

        menuItems: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MenuItemIngredient })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MenuItemIngredient",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async menuItemIngredient(
    @common.Param() params: MenuItemIngredientWhereUniqueInput
  ): Promise<MenuItemIngredient | null> {
    const result = await this.service.menuItemIngredient({
      where: params,
      select: {
        createdAt: true,
        id: true,
        ingredient: true,

        menuItems: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MenuItemIngredient })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MenuItemIngredient",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMenuItemIngredient(
    @common.Param() params: MenuItemIngredientWhereUniqueInput,
    @common.Body() data: MenuItemIngredientUpdateInput
  ): Promise<MenuItemIngredient | null> {
    try {
      return await this.service.updateMenuItemIngredient({
        where: params,
        data: {
          ...data,

          menuItems: {
            connect: data.menuItems,
          },
        },
        select: {
          createdAt: true,
          id: true,
          ingredient: true,

          menuItems: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MenuItemIngredient })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MenuItemIngredient",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMenuItemIngredient(
    @common.Param() params: MenuItemIngredientWhereUniqueInput
  ): Promise<MenuItemIngredient | null> {
    try {
      return await this.service.deleteMenuItemIngredient({
        where: params,
        select: {
          createdAt: true,
          id: true,
          ingredient: true,

          menuItems: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
