/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DecimalNullableFilter } from "../../util/DecimalNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { ComboItemTableListRelationFilter } from "../../comboItemTable/base/ComboItemTableListRelationFilter";
import { ComboItemWindowMapListRelationFilter } from "../../comboItemWindowMap/base/ComboItemWindowMapListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { EnumComboGroupComboType } from "./EnumComboGroupComboType";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { RestaurantWhereUniqueInput } from "../../restaurant/base/RestaurantWhereUniqueInput";

@InputType()
class ComboGroupWhereInput {
  @ApiProperty({
    required: false,
    type: DecimalNullableFilter,
  })
  @Type(() => DecimalNullableFilter)
  @IsOptional()
  @Field(() => DecimalNullableFilter, {
    nullable: true,
  })
  comboBasePrice?: DecimalNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  comboDescription?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ComboItemTableListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ComboItemTableListRelationFilter)
  @IsOptional()
  @Field(() => ComboItemTableListRelationFilter, {
    nullable: true,
  })
  comboItemTable?: ComboItemTableListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ComboItemWindowMapListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ComboItemWindowMapListRelationFilter)
  @IsOptional()
  @Field(() => ComboItemWindowMapListRelationFilter, {
    nullable: true,
  })
  comboItemWindowMap?: ComboItemWindowMapListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  comboName?: StringFilter;

  @ApiProperty({
    required: false,
    enum: EnumComboGroupComboType,
  })
  @IsEnum(EnumComboGroupComboType)
  @IsOptional()
  @Field(() => EnumComboGroupComboType, {
    nullable: true,
  })
  combo_type?: "Default" | "Customizable";

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  createdAt?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  isBankCoupon?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  isPlatformCoupon?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  isRestuaruantCoupon?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: () => RestaurantWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => RestaurantWhereUniqueInput)
  @IsOptional()
  @Field(() => RestaurantWhereUniqueInput, {
    nullable: true,
  })
  restaurants?: RestaurantWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  updatedAt?: DateTimeNullableFilter;
}

export { ComboGroupWhereInput as ComboGroupWhereInput };
