/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CustomerPreferenceService } from "../customerPreference.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CustomerPreferenceCreateInput } from "./CustomerPreferenceCreateInput";
import { CustomerPreference } from "./CustomerPreference";
import { CustomerPreferenceFindManyArgs } from "./CustomerPreferenceFindManyArgs";
import { CustomerPreferenceWhereUniqueInput } from "./CustomerPreferenceWhereUniqueInput";
import { CustomerPreferenceUpdateInput } from "./CustomerPreferenceUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CustomerPreferenceControllerBase {
  constructor(
    protected readonly service: CustomerPreferenceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CustomerPreference })
  @nestAccessControl.UseRoles({
    resource: "CustomerPreference",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCustomerPreference(
    @common.Body() data: CustomerPreferenceCreateInput
  ): Promise<CustomerPreference> {
    return await this.service.createCustomerPreference({
      data: {
        ...data,

        appUsers: {
          connect: data.appUsers,
        },
      },
      select: {
        appUsers: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        preferenceType: true,
        preferenceValue: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CustomerPreference] })
  @ApiNestedQuery(CustomerPreferenceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CustomerPreference",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async customerPreferences(
    @common.Req() request: Request
  ): Promise<CustomerPreference[]> {
    const args = plainToClass(CustomerPreferenceFindManyArgs, request.query);
    return this.service.customerPreferences({
      ...args,
      select: {
        appUsers: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        preferenceType: true,
        preferenceValue: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CustomerPreference })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CustomerPreference",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async customerPreference(
    @common.Param() params: CustomerPreferenceWhereUniqueInput
  ): Promise<CustomerPreference | null> {
    const result = await this.service.customerPreference({
      where: params,
      select: {
        appUsers: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        preferenceType: true,
        preferenceValue: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CustomerPreference })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CustomerPreference",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCustomerPreference(
    @common.Param() params: CustomerPreferenceWhereUniqueInput,
    @common.Body() data: CustomerPreferenceUpdateInput
  ): Promise<CustomerPreference | null> {
    try {
      return await this.service.updateCustomerPreference({
        where: params,
        data: {
          ...data,

          appUsers: {
            connect: data.appUsers,
          },
        },
        select: {
          appUsers: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          preferenceType: true,
          preferenceValue: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CustomerPreference })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CustomerPreference",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCustomerPreference(
    @common.Param() params: CustomerPreferenceWhereUniqueInput
  ): Promise<CustomerPreference | null> {
    try {
      return await this.service.deleteCustomerPreference({
        where: params,
        select: {
          appUsers: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          preferenceType: true,
          preferenceValue: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
