import { AccountRestaurantLookupCreateNestedManyWithoutRestaurantsInput } from "./AccountRestaurantLookupCreateNestedManyWithoutRestaurantsInput";
import { Decimal } from "decimal.js";
import { ComboGroupCreateNestedManyWithoutRestaurantsInput } from "./ComboGroupCreateNestedManyWithoutRestaurantsInput";
import { FavouriteRestaurantCreateNestedManyWithoutRestaurantsInput } from "./FavouriteRestaurantCreateNestedManyWithoutRestaurantsInput";
import { MenuCategoryCreateNestedManyWithoutRestaurantsInput } from "./MenuCategoryCreateNestedManyWithoutRestaurantsInput";
import { MerchantInvoiceCreateNestedManyWithoutRestaurantsInput } from "./MerchantInvoiceCreateNestedManyWithoutRestaurantsInput";
import { OrderHistoryCreateNestedManyWithoutRestaurantsInput } from "./OrderHistoryCreateNestedManyWithoutRestaurantsInput";
import { OrderPackagingFeeCreateNestedManyWithoutRestaurantsInput } from "./OrderPackagingFeeCreateNestedManyWithoutRestaurantsInput";
import { PayoutCycleCreateNestedManyWithoutRestaurantsInput } from "./PayoutCycleCreateNestedManyWithoutRestaurantsInput";
import { PayoutInformationTableCreateNestedManyWithoutRestaurantsInput } from "./PayoutInformationTableCreateNestedManyWithoutRestaurantsInput";
import { PortalUsersRelationsLookupCreateNestedManyWithoutRestaurantsInput } from "./PortalUsersRelationsLookupCreateNestedManyWithoutRestaurantsInput";
import { ReservationCreateNestedManyWithoutRestaurantsInput } from "./ReservationCreateNestedManyWithoutRestaurantsInput";
import { RestaurantDetailCreateNestedManyWithoutRestaurantsInput } from "./RestaurantDetailCreateNestedManyWithoutRestaurantsInput";
import { RestaurantPreferenceCreateNestedManyWithoutRestaurantsInput } from "./RestaurantPreferenceCreateNestedManyWithoutRestaurantsInput";
import { RestaurantsHashtagsMapCreateNestedManyWithoutRestaurantsInput } from "./RestaurantsHashtagsMapCreateNestedManyWithoutRestaurantsInput";
import { RestaurantTimeWindowMapCreateNestedManyWithoutRestaurantsInput } from "./RestaurantTimeWindowMapCreateNestedManyWithoutRestaurantsInput";
import { TaxRateInformationCreateNestedManyWithoutRestaurantsInput } from "./TaxRateInformationCreateNestedManyWithoutRestaurantsInput";

export type RestaurantCreateInput = {
  accountRestaurantLookup?: AccountRestaurantLookupCreateNestedManyWithoutRestaurantsInput;
  averageCost?: Decimal | null;
  closure_status?: "Temporarily_Closed" | "Permanently_Closed" | null;
  comboGroups?: ComboGroupCreateNestedManyWithoutRestaurantsInput;
  favouriteRestaurant?: FavouriteRestaurantCreateNestedManyWithoutRestaurantsInput;
  isActive?: boolean | null;
  isDelivery?: boolean | null;
  isDineIn?: boolean | null;
  isHidden?: boolean | null;
  isTakeaway?: boolean | null;
  menuCategories?: MenuCategoryCreateNestedManyWithoutRestaurantsInput;
  merchantInvoices?: MerchantInvoiceCreateNestedManyWithoutRestaurantsInput;
  orderHistory?: OrderHistoryCreateNestedManyWithoutRestaurantsInput;
  orderPackagingFee?: OrderPackagingFeeCreateNestedManyWithoutRestaurantsInput;
  packaging_fee_type?: "Item" | "Order" | "None" | null;
  payoutCycles?: PayoutCycleCreateNestedManyWithoutRestaurantsInput;
  payoutInformationTable?: PayoutInformationTableCreateNestedManyWithoutRestaurantsInput;
  portalUsersRelationsLookup?: PortalUsersRelationsLookupCreateNestedManyWithoutRestaurantsInput;
  reservations?: ReservationCreateNestedManyWithoutRestaurantsInput;
  restaurantDetails?: RestaurantDetailCreateNestedManyWithoutRestaurantsInput;
  restaurantIconUrl?: string | null;
  restaurantIdRef: number;
  restaurantPreferences?: RestaurantPreferenceCreateNestedManyWithoutRestaurantsInput;
  restaurantsHashtagsMap?: RestaurantsHashtagsMapCreateNestedManyWithoutRestaurantsInput;
  restaurantTimeWindowMap?: RestaurantTimeWindowMapCreateNestedManyWithoutRestaurantsInput;
  shareSlug?: string | null;
  taxRateInformation?: TaxRateInformationCreateNestedManyWithoutRestaurantsInput;
  updatedAt?: Date | null;
};
