import { AccountRestaurantLookup } from "../accountRestaurantLookup/AccountRestaurantLookup";
import { Decimal } from "decimal.js";
import { ComboGroup } from "../comboGroup/ComboGroup";
import { FavouriteRestaurant } from "../favouriteRestaurant/FavouriteRestaurant";
import { MenuCategory } from "../menuCategory/MenuCategory";
import { MerchantInvoice } from "../merchantInvoice/MerchantInvoice";
import { OrderHistory } from "../orderHistory/OrderHistory";
import { OrderPackagingFee } from "../orderPackagingFee/OrderPackagingFee";
import { PayoutCycle } from "../payoutCycle/PayoutCycle";
import { PayoutInformationTable } from "../payoutInformationTable/PayoutInformationTable";
import { PortalUsersRelationsLookup } from "../portalUsersRelationsLookup/PortalUsersRelationsLookup";
import { Reservation } from "../reservation/Reservation";
import { RestaurantDetail } from "../restaurantDetail/RestaurantDetail";
import { RestaurantPreference } from "../restaurantPreference/RestaurantPreference";
import { RestaurantsHashtagsMap } from "../restaurantsHashtagsMap/RestaurantsHashtagsMap";
import { RestaurantTimeWindowMap } from "../restaurantTimeWindowMap/RestaurantTimeWindowMap";
import { TaxRateInformation } from "../taxRateInformation/TaxRateInformation";

export type Restaurant = {
  accountRestaurantLookup?: Array<AccountRestaurantLookup>;
  averageCost: Decimal | null;
  closure_status?: "Temporarily_Closed" | "Permanently_Closed" | null;
  comboGroups?: Array<ComboGroup>;
  createdAt: Date | null;
  favouriteRestaurant?: Array<FavouriteRestaurant>;
  id: string;
  isActive: boolean | null;
  isDelivery: boolean | null;
  isDineIn: boolean | null;
  isHidden: boolean | null;
  isTakeaway: boolean | null;
  menuCategories?: Array<MenuCategory>;
  merchantInvoices?: Array<MerchantInvoice>;
  orderHistory?: Array<OrderHistory>;
  orderPackagingFee?: Array<OrderPackagingFee>;
  packaging_fee_type?: "Item" | "Order" | "None" | null;
  payoutCycles?: Array<PayoutCycle>;
  payoutInformationTable?: Array<PayoutInformationTable>;
  portalUsersRelationsLookup?: Array<PortalUsersRelationsLookup>;
  reservations?: Array<Reservation>;
  restaurantDetails?: Array<RestaurantDetail>;
  restaurantIconUrl: string | null;
  restaurantIdRef: number;
  restaurantPreferences?: Array<RestaurantPreference>;
  restaurantsHashtagsMap?: Array<RestaurantsHashtagsMap>;
  restaurantTimeWindowMap?: Array<RestaurantTimeWindowMap>;
  shareSlug: string | null;
  taxRateInformation?: Array<TaxRateInformation>;
  updatedAt: Date | null;
};
