import { AccountRestaurantLookupUpdateManyWithoutRestaurantsInput } from "./AccountRestaurantLookupUpdateManyWithoutRestaurantsInput";
import { Decimal } from "decimal.js";
import { ComboGroupUpdateManyWithoutRestaurantsInput } from "./ComboGroupUpdateManyWithoutRestaurantsInput";
import { FavouriteRestaurantUpdateManyWithoutRestaurantsInput } from "./FavouriteRestaurantUpdateManyWithoutRestaurantsInput";
import { MenuCategoryUpdateManyWithoutRestaurantsInput } from "./MenuCategoryUpdateManyWithoutRestaurantsInput";
import { MerchantInvoiceUpdateManyWithoutRestaurantsInput } from "./MerchantInvoiceUpdateManyWithoutRestaurantsInput";
import { OrderHistoryUpdateManyWithoutRestaurantsInput } from "./OrderHistoryUpdateManyWithoutRestaurantsInput";
import { OrderPackagingFeeUpdateManyWithoutRestaurantsInput } from "./OrderPackagingFeeUpdateManyWithoutRestaurantsInput";
import { PayoutCycleUpdateManyWithoutRestaurantsInput } from "./PayoutCycleUpdateManyWithoutRestaurantsInput";
import { PayoutInformationTableUpdateManyWithoutRestaurantsInput } from "./PayoutInformationTableUpdateManyWithoutRestaurantsInput";
import { PortalUsersRelationsLookupUpdateManyWithoutRestaurantsInput } from "./PortalUsersRelationsLookupUpdateManyWithoutRestaurantsInput";
import { ReservationUpdateManyWithoutRestaurantsInput } from "./ReservationUpdateManyWithoutRestaurantsInput";
import { RestaurantDetailUpdateManyWithoutRestaurantsInput } from "./RestaurantDetailUpdateManyWithoutRestaurantsInput";
import { RestaurantPreferenceUpdateManyWithoutRestaurantsInput } from "./RestaurantPreferenceUpdateManyWithoutRestaurantsInput";
import { RestaurantsHashtagsMapUpdateManyWithoutRestaurantsInput } from "./RestaurantsHashtagsMapUpdateManyWithoutRestaurantsInput";
import { RestaurantTimeWindowMapUpdateManyWithoutRestaurantsInput } from "./RestaurantTimeWindowMapUpdateManyWithoutRestaurantsInput";
import { TaxRateInformationUpdateManyWithoutRestaurantsInput } from "./TaxRateInformationUpdateManyWithoutRestaurantsInput";

export type RestaurantUpdateInput = {
  accountRestaurantLookup?: AccountRestaurantLookupUpdateManyWithoutRestaurantsInput;
  averageCost?: Decimal | null;
  closure_status?: "Temporarily_Closed" | "Permanently_Closed" | null;
  comboGroups?: ComboGroupUpdateManyWithoutRestaurantsInput;
  favouriteRestaurant?: FavouriteRestaurantUpdateManyWithoutRestaurantsInput;
  isActive?: boolean | null;
  isDelivery?: boolean | null;
  isDineIn?: boolean | null;
  isHidden?: boolean | null;
  isTakeaway?: boolean | null;
  menuCategories?: MenuCategoryUpdateManyWithoutRestaurantsInput;
  merchantInvoices?: MerchantInvoiceUpdateManyWithoutRestaurantsInput;
  orderHistory?: OrderHistoryUpdateManyWithoutRestaurantsInput;
  orderPackagingFee?: OrderPackagingFeeUpdateManyWithoutRestaurantsInput;
  packaging_fee_type?: "Item" | "Order" | "None" | null;
  payoutCycles?: PayoutCycleUpdateManyWithoutRestaurantsInput;
  payoutInformationTable?: PayoutInformationTableUpdateManyWithoutRestaurantsInput;
  portalUsersRelationsLookup?: PortalUsersRelationsLookupUpdateManyWithoutRestaurantsInput;
  reservations?: ReservationUpdateManyWithoutRestaurantsInput;
  restaurantDetails?: RestaurantDetailUpdateManyWithoutRestaurantsInput;
  restaurantIconUrl?: string | null;
  restaurantIdRef?: number;
  restaurantPreferences?: RestaurantPreferenceUpdateManyWithoutRestaurantsInput;
  restaurantsHashtagsMap?: RestaurantsHashtagsMapUpdateManyWithoutRestaurantsInput;
  restaurantTimeWindowMap?: RestaurantTimeWindowMapUpdateManyWithoutRestaurantsInput;
  shareSlug?: string | null;
  taxRateInformation?: TaxRateInformationUpdateManyWithoutRestaurantsInput;
  updatedAt?: Date | null;
};
