import { AccountRestaurantLookupListRelationFilter } from "../accountRestaurantLookup/AccountRestaurantLookupListRelationFilter";
import { DecimalNullableFilter } from "../../util/DecimalNullableFilter";
import { ComboGroupListRelationFilter } from "../comboGroup/ComboGroupListRelationFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { FavouriteRestaurantListRelationFilter } from "../favouriteRestaurant/FavouriteRestaurantListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { MenuCategoryListRelationFilter } from "../menuCategory/MenuCategoryListRelationFilter";
import { MerchantInvoiceListRelationFilter } from "../merchantInvoice/MerchantInvoiceListRelationFilter";
import { OrderHistoryListRelationFilter } from "../orderHistory/OrderHistoryListRelationFilter";
import { OrderPackagingFeeListRelationFilter } from "../orderPackagingFee/OrderPackagingFeeListRelationFilter";
import { PayoutCycleListRelationFilter } from "../payoutCycle/PayoutCycleListRelationFilter";
import { PayoutInformationTableListRelationFilter } from "../payoutInformationTable/PayoutInformationTableListRelationFilter";
import { PortalUsersRelationsLookupListRelationFilter } from "../portalUsersRelationsLookup/PortalUsersRelationsLookupListRelationFilter";
import { ReservationListRelationFilter } from "../reservation/ReservationListRelationFilter";
import { RestaurantDetailListRelationFilter } from "../restaurantDetail/RestaurantDetailListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { IntFilter } from "../../util/IntFilter";
import { RestaurantPreferenceListRelationFilter } from "../restaurantPreference/RestaurantPreferenceListRelationFilter";
import { RestaurantsHashtagsMapListRelationFilter } from "../restaurantsHashtagsMap/RestaurantsHashtagsMapListRelationFilter";
import { RestaurantTimeWindowMapListRelationFilter } from "../restaurantTimeWindowMap/RestaurantTimeWindowMapListRelationFilter";
import { TaxRateInformationListRelationFilter } from "../taxRateInformation/TaxRateInformationListRelationFilter";

export type RestaurantWhereInput = {
  accountRestaurantLookup?: AccountRestaurantLookupListRelationFilter;
  averageCost?: DecimalNullableFilter;
  closure_status?: "Temporarily_Closed" | "Permanently_Closed";
  comboGroups?: ComboGroupListRelationFilter;
  createdAt?: DateTimeNullableFilter;
  favouriteRestaurant?: FavouriteRestaurantListRelationFilter;
  id?: StringFilter;
  isActive?: BooleanNullableFilter;
  isDelivery?: BooleanNullableFilter;
  isDineIn?: BooleanNullableFilter;
  isHidden?: BooleanNullableFilter;
  isTakeaway?: BooleanNullableFilter;
  menuCategories?: MenuCategoryListRelationFilter;
  merchantInvoices?: MerchantInvoiceListRelationFilter;
  orderHistory?: OrderHistoryListRelationFilter;
  orderPackagingFee?: OrderPackagingFeeListRelationFilter;
  packaging_fee_type?: "Item" | "Order" | "None";
  payoutCycles?: PayoutCycleListRelationFilter;
  payoutInformationTable?: PayoutInformationTableListRelationFilter;
  portalUsersRelationsLookup?: PortalUsersRelationsLookupListRelationFilter;
  reservations?: ReservationListRelationFilter;
  restaurantDetails?: RestaurantDetailListRelationFilter;
  restaurantIconUrl?: StringNullableFilter;
  restaurantIdRef?: IntFilter;
  restaurantPreferences?: RestaurantPreferenceListRelationFilter;
  restaurantsHashtagsMap?: RestaurantsHashtagsMapListRelationFilter;
  restaurantTimeWindowMap?: RestaurantTimeWindowMapListRelationFilter;
  shareSlug?: StringNullableFilter;
  taxRateInformation?: TaxRateInformationListRelationFilter;
  updatedAt?: DateTimeNullableFilter;
};
