/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AccessLog } from "./AccessLog";
import { AccessLogCountArgs } from "./AccessLogCountArgs";
import { AccessLogFindManyArgs } from "./AccessLogFindManyArgs";
import { AccessLogFindUniqueArgs } from "./AccessLogFindUniqueArgs";
import { CreateAccessLogArgs } from "./CreateAccessLogArgs";
import { UpdateAccessLogArgs } from "./UpdateAccessLogArgs";
import { DeleteAccessLogArgs } from "./DeleteAccessLogArgs";
import { AppUser } from "../../appUser/base/AppUser";
import { AccessLogService } from "../accessLog.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AccessLog)
export class AccessLogResolverBase {
  constructor(
    protected readonly service: AccessLogService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AccessLog",
    action: "read",
    possession: "any",
  })
  async _accessLogsMeta(
    @graphql.Args() args: AccessLogCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AccessLog])
  @nestAccessControl.UseRoles({
    resource: "AccessLog",
    action: "read",
    possession: "any",
  })
  async accessLogs(
    @graphql.Args() args: AccessLogFindManyArgs
  ): Promise<AccessLog[]> {
    return this.service.accessLogs(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AccessLog, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AccessLog",
    action: "read",
    possession: "own",
  })
  async accessLog(
    @graphql.Args() args: AccessLogFindUniqueArgs
  ): Promise<AccessLog | null> {
    const result = await this.service.accessLog(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AccessLog)
  @nestAccessControl.UseRoles({
    resource: "AccessLog",
    action: "create",
    possession: "any",
  })
  async createAccessLog(
    @graphql.Args() args: CreateAccessLogArgs
  ): Promise<AccessLog> {
    return await this.service.createAccessLog({
      ...args,
      data: {
        ...args.data,

        appUsers: {
          connect: args.data.appUsers,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AccessLog)
  @nestAccessControl.UseRoles({
    resource: "AccessLog",
    action: "update",
    possession: "any",
  })
  async updateAccessLog(
    @graphql.Args() args: UpdateAccessLogArgs
  ): Promise<AccessLog | null> {
    try {
      return await this.service.updateAccessLog({
        ...args,
        data: {
          ...args.data,

          appUsers: {
            connect: args.data.appUsers,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AccessLog)
  @nestAccessControl.UseRoles({
    resource: "AccessLog",
    action: "delete",
    possession: "any",
  })
  async deleteAccessLog(
    @graphql.Args() args: DeleteAccessLogArgs
  ): Promise<AccessLog | null> {
    try {
      return await this.service.deleteAccessLog(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => AppUser, {
    nullable: true,
    name: "appUsers",
  })
  @nestAccessControl.UseRoles({
    resource: "AppUser",
    action: "read",
    possession: "any",
  })
  async getAppUsers(
    @graphql.Parent() parent: AccessLog
  ): Promise<AppUser | null> {
    const result = await this.service.getAppUsers(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
