import { Decimal } from "decimal.js";
import { DailyMenuItemStock } from "../dailyMenuItemStock/DailyMenuItemStock";
import { DiscountMenuItem } from "../discountMenuItem/DiscountMenuItem";
import { FavouriteMenuItem } from "../favouriteMenuItem/FavouriteMenuItem";
import { ItemPackagingFee } from "../itemPackagingFee/ItemPackagingFee";
import { MenuItemIngredient } from "../menuItemIngredient/MenuItemIngredient";
import { MenuItemsHashtagsMap } from "../menuItemsHashtagsMap/MenuItemsHashtagsMap";
import { MenuItemsOptionsGroup } from "../menuItemsOptionsGroup/MenuItemsOptionsGroup";
import { MenuItemsWindowMap } from "../menuItemsWindowMap/MenuItemsWindowMap";
import { MenuSubCategory } from "../menuSubCategory/MenuSubCategory";

export type MenuItem = {
  availableQuantity: number | null;
  basePrice: Decimal | null;
  containsEgg: boolean | null;
  createdAt: Date | null;
  dailyMenuItemStock?: Array<DailyMenuItemStock>;
  description: string | null;
  discountMenuItem?: Array<DiscountMenuItem>;
  favouriteMenuItems?: Array<FavouriteMenuItem>;
  id: string;
  imageUrl: string | null;
  ingredients: string | null;
  isActive: boolean | null;
  isDeliverable: boolean | null;
  isDineinAvailable: boolean | null;
  isLimitedStock: boolean | null;
  isPickup: boolean | null;
  isVegetarian: boolean | null;
  itemPackagingFee?: Array<ItemPackagingFee>;
  menuItemIngredients?: Array<MenuItemIngredient>;
  menuItemsHashtagsMap?: Array<MenuItemsHashtagsMap>;
  menuItemsOptionsGroups?: Array<MenuItemsOptionsGroup>;
  menuItemsWindowMap?: Array<MenuItemsWindowMap>;
  menuSubCategories?: MenuSubCategory;
  name: string | null;
  preparationTime: number | null;
  shareSlug: string | null;
  updatedAt: Date | null;
};
